[tool.locust]
locustfile = "locustfile.py"
headless = false
# master = true
# expect-workers = 5
host = "http://localhost:8080"
users = 100
spawn-rate = 10
run-time = "10m"
# tags = ["Critical", "Normal"]
csv = "./results/locust"