[tool.locust]
locustfile = "locustfile.py"
headless = false
# master = true
# expect-workers = 5
host = "http://localhost:8080"
users = 10000
spawn-rate = 1000
run-time = "10m"
# tags = ["Critical", "Normal"]
csv = "./results/locust"